# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lbastien <lbastien@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/23 18:05:08 by lbastien          #+#    #+#              #
#    Updated: 2024/03/23 18:10:18 by lbastien         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

SRC = megaphone.cpp

all: $(NAME)

$(NAME):
	g++ $(SRC) -o $(NAME)

clean:
	rm -f $(NAME)

fclean: clean

re: clean all